[theme]
primaryColor = "#3879FA"
backgroundColor = "#FCF8F3"
secondaryBackgroundColor = "#F2F2F2"
textColor = "#1F1F1F"
font = "sans serif"

[server]
enableStaticServing = true

[client]
showErrorDetails = true
toolbarMode = "viewer"

[logger]
level = "info"
